# Site settings
author: Keith Filkins
title: Newby to Ruby
header-img: img/home-bg.png
email: kafilkins@me.com
copyright_name: Keith Filkins
description: > # this means to ignore newlines until "baseurl:"
  My First CLI Data Gem Portfolio Project
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kafilkins

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
